networks:
  govtech_ctsg:
    driver: bridge

services:
  database:
    container_name: govtech_ctsg_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .docker/postgre:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - govtech_ctsg

  pgadmin:
    container_name: govtech_ctsg_db_explorer
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - .docker/pgadmin:/var/lib/pgadmin
    ports:
      - "5433:80"
    networks:
      - govtech_ctsg
    depends_on:
      - database

  govaa_backend:
    container_name: govaa_backend
    extends:
      file: docker-compose-base.yml
      service: nx-app-base
    command: yarn nx run govaa-be:serve:production
    ports:
      - "7500:7500"
    networks:
      - govtech_ctsg
    depends_on:
      - database

  backend:
    container_name: govtech_ctsg_backend
    extends:
      file: docker-compose-base.yml
      service: nx-app-base
    command: yarn nx run surveysg-be:serve:production
    ports:
      - "7501:7501"
    networks:
      - govtech_ctsg
    depends_on:
      - govaa_backend

  frontend:
    container_name: govtech_ctsg_frontend
    extends:
      file: docker-compose-base.yml
      service: nx-app-base
    command: yarn nx run surveysg-fe:serve-static --host=0.0.0.0 --port=7502
    ports:
      - "7502:7502"
    networks:
      - govtech_ctsg
    depends_on:
      - backend
